application: #APPNAME
version: 1
runtime: python
api_version: 1

handlers:
  url: /static
  static_dir: public	
  url: /static/scripts
  static_dir: public/scripts
- url: /static/css
  static_dir: public/stylesheets
- url: /static/images
  static_dir: /public/media
  url: /docs
  static_dir: app/static/docs
  url: /.*
  script: pow_gae.py